#!/bin/bash

NAME=$1
FILE=$2

echo "Creating database ${NAME}..."
mysql -u mysql -e "CREATE DATABASE ${NAME}"

echo "Importing database ${NAME} from ${FILE} ..."
mysql -u mysql -D ${NAME} < ${FILE}

echo "Analyzing databases..."
mysqlcheck --auto-repair --analyze ${NAME}
