#!/bin/bash

NAME=$1
USER=$2
PASS=$3

echo "Creating user..."

mysql -uroot -proot -e "CREATE USER '${USER}'@'%' IDENTIFIED BY '${PASS}';"
mysql -uroot -proot -e "GRANT ALL PRIVILEGES ON ${NAME}.* TO '${USER}'@'%' IDENTIFIED BY '${PASS}';"
