#!/bin/bash

# wait-port <hostname> <port> <limit>
#
# Checks <hostname>:<port> to see if there's a listener.  Checks every tenth of a second until it gets to <limit> seconds

hostname=$1
port=$2
limit=$3
countlimit=$(( $limit * 10 ))

for i in `seq 1 $countlimit`; do
	exitcount=$i
	nc -z $hostname $port
	RETVAL=$?
	if [ "$RETVAL" -lt 1 ]; then
		break
	fi
	sleep 0.1
done

if [ "$exitcount" -eq "$countlimit" ]; then
	echo "Couldn't connect to $hostname in $limit seconds; exiting" >&2
	exit 1
fi
