#!/bin/bash

export MTK_DUMP_HOSTNAME=127.0.0.1
export MTK_DUMP_USERNAME=tmp
export MTK_DUMP_PASSWORD=tmp
export MTK_DUMP_DATABASE=tmp

SOURCE=$1
TARGET=$2

echo "Starting MySQL"
mysql-start &
while ! nc -z localhost 3306; do
  sleep 0.1
done

echo "Creating temporary database"
database-create $MTK_DUMP_DATABASE $SOURCE

echo "Creating temporary account"
user-create $MTK_DUMP_DATABASE $MTK_DUMP_USERNAME $MTK_DUMP_PASSWORD

echo "Dumping sanitized database"
mtk dump > $TARGET

echo "Stopping MySQL"
mysql-stop
