name: Functional Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Build MTK
        run: make build

      - name: Start MySQL
        run: sudo /etc/init.d/mysql start

      - name: "Test: Dump"
        run: |
          mysql -e 'CREATE DATABASE dump_test;' -uroot -proot
          mysql -uroot -proot dump_test < .github/workflows/functional-test/fixtures/dump/db.sql
          bin/mtk-linux-amd64 dump dump_test --port=3306 --user=root --password=root --host=127.0.0.1 > mtk-dump.sql
          mysql -e 'DROP DATABASE dump_test;' -uroot -proot
          sed '$d' mtk-dump.sql > mtk-dump-clean.sql
          mysql -e 'CREATE DATABASE dump_test;' -uroot -proot
          mysql -uroot -proot dump_test < mtk-dump-clean.sql
          diff -q .github/workflows/functional-test/fixtures/dump/db.sql mtk-dump-clean.sql

      - name: "Test: Dump Tables"
        run: |
          mysql -e 'CREATE DATABASE dump_files_test;' -uroot -proot
          # Reusing the same fixture as our dump test
          mysql -uroot -proot dump_files_test < .github/workflows/functional-test/fixtures/dump/db.sql
          mkdir /tmp/dumps
          bin/mtk-linux-amd64 dump-tables dump_files_test --port=3306 --user=root --password=root --host=127.0.0.1 /tmp/dumps

      - name: 📋 Archive Output
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: sql-dumps
          path: |
            /tmp/dumps
