name: Create and publish a Github Package

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Git clone the repository
        uses: actions/checkout@v5

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 📦 Install Mise
        run: |
          curl https://mise.run | sh
          mise install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🧪 Release
        run: |
          mise run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
